export const ActionTypes = {
  SET_ADMIN: "SET_ADMIN",
  SET_USER: "SET_USER",
  FETCH_USERS: "FETCH_USERS",
  FETCH_ORGS: "FETCH_ORGS",
  SEARCH_ORGS: "SEARCH_ORGS",
  FETCH_ONE_ORG: "FETCH_ONE_ORG",
};
